# Generated by Django 3.2.6 on 2021-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpkey', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'otp',
                'managed': False,
            },
        ),
    ]
