# Generated by Django 3.2.6 on 2021-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
    ]
