# Generated by Django 3.2.6 on 2021-09-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0003_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
