# Generated by Django 3.2.6 on 2021-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0004_delete_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
