# Generated by Django 3.2.6 on 2021-09-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0006_auto_20210919_1503'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorylist',
            table='categorylist',
        ),
    ]
